<ips:template parameters="$comment, $item, $url" />

<div data-embedInfo-maxSize='500' class='ipsRichEmbed'>
	{template="embedHeader" group="embed" app="core" params="$comment, \IPS\Member::loggedIn()->language()->addToStack( 'x_commented_cms_embed', FALSE, array( 'sprintf' => array( $comment->author()->name, $item->indefiniteArticle() ) ) ), $comment->mapped('date'), $url"}
	<div class='ipsPad'>
		<div class='ipsRichEmbed_originalItem ipsAreaBackground_reset ipsSpacer_bottom ipsType_blendLinks'>
			<div>
				{{if $item->record_image}}
					{{$image = \IPS\File::get( "cms_Records", $item->record_image );}}
				{{elseif count( $item->contentImages() )}}
					{{$attachType = key( $item->contentImages()[0] );}}
					{{$image = \IPS\File::get( $attachType, $item->contentImages()[0][ $attachType ] );}}
				{{endif}}

				{{if $image}}
					<div class='ipsRichEmbed_masthead ipsRichEmbed_mastheadBg ipsType_center'>
						<a href='{$url}' style='background-image: url( "{expression="str_replace( array( '(', ')' ), array( '\(', '\)' ), $image->url )"}" )'>
							<img src='{$image->url}' class='ipsHide' alt=''>
						</a>
					</div>
				{{endif}}
				<div class='ipsPad'>
					{template="embedOriginalItem" group="embed" app="core" params="$item, TRUE, \IPS\Theme::i()->getTemplate( 'global', 'cms' )->embedRecordItemSnippet( $item ) "}
				</div>
			</div>
		</div>

		<div class='ipsType_richText ipsType_medium' data-truncate='3'>
			{$comment->truncated(TRUE)|raw}
		</div>

		{{if \IPS\IPS::classUsesTrait( $comment, 'IPS\Content\Reactable' ) and count( $comment->reactions() ) and settings.reputation_enabled}}
			<ul class='ipsList_inline ipsSpacer_top ipsSpacer_half'>
				<li>
					{template="reactionOverview" app="core" group="global" params="$comment, TRUE, 'small'"}
				</li>
			</ul>
		{{endif}}
	</div>
</div>