<?php

$lang = array(

	'__app_forums'					=> "Forums",
	'frontnavigation_forums'		=> "Forums",
	'__indefart_post'				=> "a post in a topic",
	'__indefart_topic'				=> "a topic",
	'__indefart_answer'				=> "an answer to a question",
	'__indefart_question'			=> "a question",
	'__defart_post'					=> "post in a topic",
	'__defart_topic'				=> "topic",
	'__defart_answer'				=> "answer to a question",
	'__defart_question'				=> "question",
	'topic_container'				=> "Forum",
	'search_contextual_item_forums'	=> "This Forum",
	'search_contextual_item_topic'	=> "This Topic",
	
	'module__forums_forums'			=> "Forums",
	'module__forums_stats'			=> "Statistics",
	'filestorage__forums_Icons'		=> "Forum Icons",
	'post'							=> "Post",
	'post_lc'						=> "post",

	'editor__forums_Forums'			=> "Forums and Topics",
	'acp_search_title_forums_Forums'	=> "Forums",

	/* !ACP Menu */
	'menu__forums_forums'			=> "Forums",
	'menu__forums_forums_forums'	=> "Forums",
	'menu__forums_forums_savedActions' => "Saved Actions",
	'menu__forums_forums_rss'		=> "RSS/Atom Feeds",
	
	'menu__forums_stats'			=> "Forums",
	'menu__forums_stats_topics'		=> "New Topics",
	'menu__forums_stats_posts'		=> "New Posts",
	
	/* !ACP Restrictions */
	'r__forums'						=> "Forums",
	'r__forums_manage'				=> "Can view forums?",
	'r__forums_add'					=> "Can create forums?",
	'r__forums_edit'				=> "Can edit forums?",
	'r__forums_perms'				=> "Can manage forum permissions?",
	'r__forums_massManageContent'	=> "Can mass move/delete topics in forums?",
	'r__forums_delete'				=> "Can delete forums?",
	'r__archive_manage'				=> "Can manage archive settings?",
	'r__settings_access'			=> "Can access settings?",
	'r__forum_settings'				=> "Can manage forums settings?",
	'r__rss'						=> "Feeds",
	'r__rss_manage'					=> "Can view feed imports?",
	'r__rss_add'					=> "Can create feed imports?",
	'r__rss_edit'					=> "Can edit feed imports?",
	'r__rss_delete'					=> "Can delete feed imports?",
	'r__rss_run'					=> "Can run feed imports?",
	'r__savedActions'				=> "Saved Actions",
	'r__savedActions_manage'		=> "Can view saved actions?",
	'r__savedActions_add'			=> "Can create saved actions?",
	'r__savedActions_edit'			=> "Can edit saved actions?",
	'r__savedActions_delete'		=> "Can delete saved actions?",
	'r__topics'						=> "New Topic Statistics",
	'r__topics_manage'				=> "Can view statistics about new topics",
	'r__posts'						=> "New Post Statistics",
	'r__posts_manage'				=> "Can view statistics about new posts",
	
	/* !Moderator Permissions */
	'modperms__core_Content_forums_Topic' => "Forums",
	'can_pin_topic'					=> "Can pin topics/questions?",
	'can_unpin_topic'				=> "Can unpin topics/questions?",
	'can_feature_topic'				=> "Can feature topics/questions?",
	'can_unfeature_topic'			=> "Can unfeature topics/questions?",
	'can_edit_topic'				=> "Can edit topics/questions?",
	'can_hide_topic'				=> "Can hide topics/questions?",
	'can_unhide_topic'				=> "Can unhide topics/questions?",
	'can_view_hidden_topic'			=> "Can view hidden topics/questions?",
	'can_move_topic'				=> "Can move topics/questions?",
	'can_move_topic_desc'			=> "Will be able to move topics/questions only between the forums they have permission to moderate, not to any other forum.",
	'can_lock_topic'				=> "Can lock topics/questions?",
	'can_unlock_topic'				=> "Can unlock topics/questions?",
	'can_reply_to_locked_topic'		=> "Can reply to locked topics/questions?",
	'can_delete_topic'				=> "Can delete topics/questions?",
	'can_split_merge_topic'			=> "Can split and merge topics/questions?",
	'can_edit_post'					=> "Can edit posts/answers?",
	'can_hide_post'					=> "Can hide posts/answers?",
	'can_unhide_post'				=> "Can unhide posts/answers?",
	'can_view_hidden_post'			=> "Can view hidden posts/answers?",
	'can_delete_post'				=> "Can delete posts/answers?",
	'can_read_all_topics'			=> "Can view all topics/questions?",
	'can_read_all_topics_desc'		=> "Some forums are set up to only show topics/questions to the user that posted them. When this setting is enabled, the moderator will be able to view topics/questions they did not post in those forums.",
	'can_set_best_answer'			=> "Can set best answer for questions?",
	'can_feature_comments_topic'	=> "Can recommend posts on a topic?",
	'can_unfeature_comments_topic'	=> "Can remove post recommendations on a topic?",
	'can_add_item_message_topic'	=> "Can add messages to topics?",
	'can_edit_item_message_topic'	=> "Can edit messages on topics?",
	'can_delete_item_message_topic'	=> "Can delete messages on topics?",
	
	/* !Generic Words & Phrases */
	'forums'						=> "Forums",
	'forums_sg'						=> "Forum",
	'forums_add_child'				=> "Create Subforum",
	'forums_add_child_cat'			=> "Create Forum",
	
	/* !ACP Forum Settings */
	'forum_name'					=> "Name",
	'forum_description'				=> "Description",
	'forum_description_placeholder'	=> "Add a description...",
	'forum_type'					=> "Type",
	'forum_type_normal'				=> "Discussions",
	'forum_type_normal_desc'		=> "Users can start topics that other users can reply to. Replies are shown in the order they're posted.",
	'forum_type_qa'					=> "Questions",
	'forum_type_qa_desc'			=> "Users can ask questions that other users can post answers to. Answers can then be rated by other users and the highest rated answers are shown first.",
	'forum_type_category'			=> "Category",
	'forum_type_category_desc'		=> "Container for other forums. Nothing can be posted directly within them.",
	'forum_type_redirect'			=> "Redirect",
	'forum_type_redirect_desc'		=> "Redirects users to another location when clicked on.",
	'forum_password_on'				=> "Password protected?",
	'forum_password_on_desc'		=> "When enabled, users who have permission to access the forum will need to provide the password. Users who do not have permission to access the forum will not be prompted for the password. The password applies only to this forum, if this forum has subforums, the password will not be required for them.<br>Topics posted in a password protected forum will not show in any sidebar, header or footer blocks, and notifications for new topics and posts will not be sent.",
	'forum_password'				=> "Password",
	'forum_password_override'		=> "No Password Required",
	'forum_display'					=> "Display Settings",
	'forum_topicfilter'				=> "Default filter",
	'forum_rules'					=> "Rules",
	'forum_show_rules'				=> "Show Rules?",
	'forum_show_rules_none'			=> "Do not show",
	'forum_show_rules_link'			=> "Show link to rules",
	'forum_show_rules_link_desc'	=> "The rules will be shown on a separate page with a link added in the forum header",
	'forum_show_rules_full'			=> "Show rules",
	'forum_show_rules_full_desc'	=> "The rules will be shown inline in the forum header",
	'forum_rules_title'				=> "Rules Title",
	'forum_rules_text'				=> "Rules",
	'forum_settings'				=> "Forum Settings",
	'posting_settings'				=> "Posting Settings",
	'forum_allow_poll'				=> "Allow Polls?",
	'posts'							=> "Posts",
	'forum_preview_posts'			=> "Posts must be approved?",
	'forum_preview_posts_qa'		=> "Posts must be approved?",
	'forum_preview_posts_topics'	=> "New Topics",
	'forum_preview_posts_questions'	=> "New Questions",
	'forum_preview_posts_posts'		=> "Replies",
	'forum_preview_posts_answers'	=> "Answers",
	'forum_inc_postcount'			=> "Increase Content Counts?",
	'forum_inc_postcount_desc'		=> "If disabled, the user's total number of content items will not increase when a user posts in this forum. You may want to disable this for forums for posting test messages, etc.",
	'forum_redirect_url'			=> "Redirect URL",
	'forum_redirect_hits'			=> "Redirect Count",
	'forum_redirect_hits_desc'		=> "The number of times users have clicked on the forum and been redirected, which is shown in the list of forums. This number automatically increases, but you can manually adjust it here.",
	'forum_permission_custom_error'	=> "Custom No Permission Error",
	'forum_permission_custom_error_desc' => "If provided, this message will be displayed if a user who does not have permission to access this forum tries to access it.",
	'forum_permerror_placeholder'	=> "Add an error message...",
	'forum_skin_id'					=> "Theme Override",
	'forum_skin_id_desc'			=> "When viewing this forum, the selected theme will be used regardless of the user's preference.",
	'forum_skin_id_default'			=> "-Do not override-",
	'forum_display_forum'			=> "Forum Display",
	'forum_display_topic'			=> "Topic Display",
	'forum_display_question'		=> "Question Display",
	'forum_forum_allow_rating'		=> "Enable Star Ratings?",
	'forum_forum_allow_rating_desc'	=> "You can control which groups can rate in the <a href='{internal.app=core&module=members&controller=groups}'>Group Settings</a>",
	'posting_requirements'			=> "Posting Requirements",
	'forum_min_posts_view'			=> "Minimum content count to see forum",
	'forum_min_posts_post'			=> "Minimum content count to post",
	'forum_can_view_others'			=> "Users can see topics posted by other users?",
	'forum_can_view_others_desc'	=> "Moderators can (where they have permission) see all topics. You can use this setting to create a forum where users can communicate privately with staff.<br>Topics posted in a forum that doesn't allow others to view topics will not show in any sidebar, header or footer blocks.",
	'forum_can_view_others_qa'		=> "Users can see questions asked by other users?",
	'forum_can_view_others_qa_desc'	=> "Moderators can (where they have permission) see all questions. You can use this setting to create a private support forum.",
	'forum_permission_showtopic'	=> "Users without read permission can open forum?",
	'forum_permission_showtopic_desc' => "If a user does have permission to see the forum but not to read the topics, this setting controls whether or not they can open the forum and see the topic titles.",
	'forum_permission_showtopic_qa'	=> "Users without read permission can open forum?",
	'forum_permission_showtopic_qa_desc' => "If a user does have permission to see the forum but not to read the questions, this setting controls whether or not they can open the forum and see the question titles.",
	'forum_disable_sharelinks'		=> "Enable Sharing?",
	'forum_disable_sharelinks_desc' => "<a href='{internal.app=core&module=promotion&controller=sharelinks}'>Sharing Settings</a>",
	'forum_tag_predefined'			=> "Defined Tags",
	'forum_tag_predefined_unlimited'=> "Use default",
	'forum_tag_predefined_desc'		=> "If using a closed system, users will have to choose from these tags. If using an open system, tags entered here will show as suggestions.",
	'forum_ipseo_priority'			=> "Sitemap Priority",
	'forum_ipseo_priority_desc'		=> "The priority value in a sitemap file indicates to search engines how important a page is compared to other pages on the site. <a href='{internal.app=core&module=promotion&controller=seo&tab=sitemap}'>Sitemap Settings</a>",
	'forum_viglink'					=> "Enable VigLink?",
	'forum_qa_rate_questions'		=> "Who can rate questions?",
	'forum_qa_rate_questions_desc'	=> "Questions that have been rated the best within the last 30 days will show under 'Popular Questions' in the forum home.",
	'forum_qa_rate_answers'			=> "Who can rate answers?",
	'forum_qa_rate_answers_desc'	=> "Answers are ordered with the best rated answers first.",
	'bw_enable_answers_member'		=> "User who asked question can choose the best answer?",
	'bw_enable_answers_member_desc'	=> "The best answer is always displayed above all other answers.",
	'forum_icon'					=> "Icon",
	'forum_icon_desc'				=> "The icon displays next to the forum in the forum list. It will automatically be faded out to indicate if there are no unread topics within the forum.<br>If none is provided, the default icon will be used.",
	'forum_parent_id'				=> "Parent Forum",
	'forum_parent_id_error'			=> "Only categories can have no parent.",
	'forums_posts_per_page'			=> "Posts per page",
	'add_forum'						=> "Add Forum",
	'edit_forum'					=> "Edit Forum",
	'node_no_parentf'				=> "No Parent",
	'forum_use_feature_color'		=> "Use a Feature Color?",
	'forum_use_feature_color_desc'	=> "A feature color will show the forum title as a badge when used in a description.",
	'forum_feature_color'			=> "Feature color",
	
	'rebuilding_starter_ids'		=> "Rebuilding topic starter IDs",

	/* !Report Center */
	'forums_topic_post'				=> "Forum Posts",
	'forums_topic'					=> "Forum Topics",
	'forums_topic_pl'				=> "Topics",
	
	/* !ACP General Settings */
	'menu__forums_forums_settings'	=> "Settings",
	'forums_popular_now'			=> "Popular Now",
	'forums_popular_now_desc'		=> "Topics which are Popular Now are highlighted in the list.",
	'posts_in_the_last'				=> "posts in the last",
	'acplogs__forums_settings'		=> "Updated forums settings",
	'topics'						=> "Topics",
	'questions'						=> "Questions",
	'topic_settings'				=> "Topic Settings",
	'question_settings'				=> "Question Settings",
	'forums_questions_downvote'		=> "Questions can be negatively rated?",
	'forums_answers_downvote'		=> "Answers can be negatively rated?",
	'forums_new_questions'			=> "New Questions",
	'forums_new_questions_desc'		=> "New questions are highlighted at the top of the page when viewing a forum.",
	'forums_new_questions_best'		=> "Questions where a best answer has not been chosen.",
	'forums_new_questions_any'		=> "Questions which have not received any answers.",
	'forums_rss'					=> "Enable RSS feeds?",
	'forums_rss_desc'				=> "Only content that is available to guests will be shown. For more options, create a <a href='{internal.app=core&module=discovery&controller=rss}'>Custom RSS Feed</a>",
	'forums_topics_per_page'		=> "Topics per page",
	'forums_default_view'			=> "Default forum view",
	'forums_default_view_table'		=> "Table: A traditional forum index table view",
	'forums_default_view_grid'		=> "Grid: Display forums as cards in a grid",
	'forums_default_view_fluid'		=> "Fluid: A simpler dynamic listing topics with a forum filter box",
	'forums_default_view_fluid_desc' => "Fluid view works best with fewer forums with less complex hierarchies. The fluid view selector will only display up to three levels deep.",
	'forums_default_view_choose'	 => "Members can choose?",
	'forums_default_view_choose_desc'	=> "Select the views you will allow members to choose from",
	'forums_default_view_choose_none' => "Do not allow members to choose",
	'forums_fluid_pinned'	=> "Honor Pinned Topics",
	'forums_fluid_pinned_desc'	=> "Show pinned topics from selected forums at the top of the topic list when fluid mode is used",
	'forums_default_view_choose_error' => "You must select at least two views for members to choose from",
	
	/* !Archiving */
	'archiving'						=> "Archiving",
	'archiving_blurb'				=> "If you have a very large site, it can be beneficial to reduce the size of the database table storing posts. Archiving topics is an alternative to deleting which allows them to still exist and be viewed as normal, but moves them to a separate database table. Archived topics cannot be posted in or edited, and will not show in search results. You can unarchive topics after they've been archived if you change your mind.",
	'archive_topics_where'			=> "Archive topics when <em>all</em> of the following conditions are true...",
	'archive_topic_forums'			=> "In forums",
	'archive_topic_not_forums'		=> "In forums",
	'archive_topic_pinned'			=> "Pinned/Unpinned",
	'archive_topic_featured'		=> "Featured/Unfeatured",
	'archive_topic_state'			=> "Locked/Unlocked",
	'unlocked'						=> "Unlocked",
	'archive_topic_approved'		=> "Hidden/Unhidden",
	'unhidden'						=> "Unhidden",
	'archive_topic_poll'			=> "Poll",
	'topic_has_poll'				=> "Has poll",
	'topic_does_not_have_poll'		=> "Does not have poll",
	'poll_with_recent_vote'			=> "Last poll vote: %s",
	'archive_topic_post'			=> "Posts",
	'archive_topic_view'			=> "Views",
	'archive_topic_rating'			=> "Rating",
	'archive_topic_starter'			=> "Started By",
	'archive_topic_starter_not'		=> "Started By",
	'archive_topics_not_where'		=> "But not when <em>any</em> of the following conditions are true...",
	'archive_not_topic_post'		=> "Posts",
	'archive_not_topic_view'		=> "Views",
	'archive_not_topic_rating'		=> "Rating",
	'archive_last_post'				=> "Last Post",
	'archive_not_last_post'			=> "Last Post",
	'archive_storage'				=> "Archived Post Storage",
	'archive_storage_location'		=> "Move archived posts to",
	'archive_storage_location_desc'	=> "If you have already set up archiving and want to change the storage location, you will manually need to move the posts which have already been archived. Contact technical support for assistance.",
	'archive_storage_location_local'=> "A database table within the same database as the rest of the site",
	'archive_storage_location_remote'=> "A remote database",
	'greater_than'					=> "More than",
	'less_than'						=> "Less than",
	'any_time'						=> "Any time",
	'archive_rules_effects'			=> "Number of topics that will be archived with selected rules",
	'forum_sort_key'				=> "Default sort order",
	'forum_sort_key_qa'				=> "Default sort order",
	'archive_settings'				=> "Archiving Settings",
	'archive_on'					=> "Enable Archiving?",
	'task__archive'					=> "Archives posts.",
	'task__unarchive'				=> "Unarchives posts.",
	'remove_archive_exlude'			=> "Allow this topic to be archived",
	'unarchive'						=> "Unarchive",
	'unarchive_confirm'				=> "Unarchiving this topic will exclude it from being archived again in the future. After confirming, it will take about {# [1:minute][?:minutes]} until the topic is actually unarchived.",
	'uanrchive_settings_change'		=> "Some topics that are already archived no longer match your archive settings. Would you like to unarchive them?",
	'restore_unmatched_settings'	=> "Yes, restore topics that do not match the new archive settings",
	'leave_archived_topics'			=> "No, keep all currently archived topics as archived",
	'archive_remote_sql_host'		=> "Host",
	'archive_remote_sql_user'		=> "Username",
	'archive_remote_sql_pass'		=> "Password",
	'archive_remote_sql_database'	=> "Database Name",
	'archive_remote_sql_database_desc' => "The database must be already created. If you're not sure how to create a database, contact your hosting provider for assistance.",
	'archive_sql_port'				=> "Port",
	'archive_sql_port_desc'			=> "If you're not sure, leave at the default value.",
	'archive_sql_socket'			=> "Socket",
	'archive_sql_socket_desc'		=> "If not provided, the server's default setting will be used. If you're not sure, leave at the default value.",
	'archive_sql_tbl_prefix'		=> "Table Prefix",
	'archive_sql_tbl_prefix_desc'	=> "If provided, the archive database table created will be prefixed with the value provided. It is recommended this is left blank.",
	'archive_remote_db_error'		=> "There was a problem with the remote database details provided: %s",
	'acplogs__archive_settings'		=> "Edited Archive Settings",
	
	/* Permissions */
	'perm_forum_perm__label'		=> '',
	'perm_forum_perm__view'			=> 'See Forum',
	'perm_forum_perm__view_rest'	=> "See Forum<br><small>(with {# [1:item][?:items]} of content)</small>",
	'perm_forum_perm__read'			=> "Read Topics",
	'perm_forum_perm__read_pass'	=> "Read Topics<br><small>(if password is provided)</small>",
	'perm_forum_perm__read_qa'		=> "Read Questions",
	'perm_forum_perm__read_qa_pass'	=> "Read Questions<br><small>(if password is provided)</small>",
	'perm_forum_perm__read2'		=> "Read Own Topics",
	'perm_forum_perm__read2_pass'	=> "Read Own Topics<br><small>(if password is provided)</small>",
	'perm_forum_perm__read2_qa'		=> "Read Own Questions",
	'perm_forum_perm__read2_qa_pass'=> "Read Own Questions<br><small>(if password is provided)</small>",
	'perm_forum_perm__add'			=> "Post New Topics",
	'perm_forum_perm__add_rest'		=> "Post New Topics<br><small>(with {# [1:item][?:items]} of content)</small>",
	'perm_forum_perm__reply'		=> "Reply To Topics",
	'perm_forum_perm__reply_rest'	=> "Reply To Topics<br><small>(with {# [1:item][?:items]} of content)</small>",
	'perm_forum_perm__add_qa'		=> "Ask New Questions",
	'perm_forum_perm__add_qa_rest'	=> "Ask New Questions<br><small>(with {# [1:item][?:items]} of content)</small>",
	'perm_forum_perm__reply_qa'		=> "Post Answers",
	'perm_forum_perm__reply_qa_rest'=> "Post Answers<br><small>(with {# [1:item][?:items]} of content)</small>",
	'perm_forum_perm__attachments'	=> "Download Attachments",
	
	/* !Front-End */
	'posts_number'					=> "{# [1:post][?:posts]}",
	'posts_no_number'				=> "{!# [1:post][?:posts]}",
	'replies_number'				=> "{# [1:reply][?:replies]}",
	'replies_no_number'				=> "{!# [1:reply][?:replies]}",
	'redirect_hits'					=> "{# [1:visit][?:visits]} to this link",
	'answers_number'				=> "{# [1:answer][?:answers]}",
	'answers_no_number'				=> "{!# [1:answer][?:answers]}",
	'votes_number'					=> "{# [-1:vote][1:vote][?:votes]}",
	'votes_no_number'				=> "{!# [-1:vote][1:vote][?:votes]}",
	'queued_topics_badge'			=> "{# queued [1:topic][?:topics]}",
	'queued_posts_badge'			=> "{# queued [1:post][?:posts]}",
	'queued_topics'					=> "Unapproved topics",
	'queued_posts'					=> "Topics with unapproved posts",
	'start_new_topic'				=> "Start new topic",
	'start_new_topic_lc'			=> "start new topic",
	'start_new_topic_desc'			=> "Start a new topic in this forum",
	'ask_a_question'				=> "Ask a question",
	'ask_a_question_lc'				=> "ask a question",
	'ask_a_question_desc'			=> "Ask a question in this forum",
	'answer_this_question'			=> "Answer this question",
	'reply_to_this_topic'			=> "Reply to this topic",
	'mark_forum_read'				=> "Mark forum as read",
	'mark_forum_read_title'			=> "Mark all topics in this forum as read",
	'forum_password_bad'			=> "Password Incorrect.",
	'topic_details'					=> "Topic Details",
	'topic_mainTab'					=> "Content",
	'question_mainTab'				=> "Content",
	'question_title'				=> "Question",
	'topic_title'					=> "Title",
	'topic_tags'					=> "Tags",
	'topic_content'					=> '',
	'topic_auto_follow'				=> "",
	'topic_auto_follow_suffix'		=> "Notify me of replies",
	'topic_pollTab'					=> "Poll",
	'topic_poll'					=> "",
	'topic_open_time'				=> "Unlock time",
	'topic_close_time'				=> "Lock time",
	'topic_type'					=> "Filter",
	'all_topics'					=> "All",
	'open_topics'					=> "Unlocked",
	'popular_now'					=> "Popular now",
	'locked_topics'					=> "Locked",
	'poll'							=> "Poll",
	'moved_topics'					=> "Moved",
	'topics_i_started'				=> "Topics I started",
	'topics_i_posted_in'			=> "Topics I've posted in",
	'questions_i_asked'				=> "Questions I asked",
	'questions_i_posted_in'			=> "Questions I've posted an answer to",
	'question_answered'				=> "Questions with Best Answers",
	'question_not_answered'			=> "Questions without Best Answers",
	'last_post'						=> "Last post date",
	'last_poster'					=> "Name of last poster",
	'topic_starter'					=> "Name of topic starter",
	'question_asker'				=> "Name of user who asked question",
	'topic_started'					=> "Start Date",
	'topic_started_date'			=> "Started %s",
	'replies'						=> "Replies",
	'sort_direction'				=> "Sort Direction",
	'sort_num_replies'				=> "Most Replies",
	'sort_question_rating'			=> "Most Votes",
	'asc'							=> "Ascending (oldest first/alphabetically)",
	'desc'							=> "Descending (newest first)",
	'time_frame'					=> "Last Reply",
	'show_all'						=> "Anytime",
	'since_last_visit'				=> "My Last Login (%s)",
	'forum_home'					=> "Forum Home",
	'all_questions'					=> "All questions in this forum",
	'featured_question'				=> "Featured question",
	'most_popular_questions'		=> "Most Popular Questions",
	'from_the_past_30_days'			=> "From the past 30 days",
	'explore_questions_title'		=> "Explore Questions",
	'new_questions'					=> "New Questions",
	'awaiting_an_answer'			=> "Awaiting an answer",
	'best_answer_by'				=> "Best answer by %s, %s",
	'ask_byline'					=> "Asked by %s, %s",
	'ask_byline_itemprop'			=> "Asked by %s, %s",
	'ask_byline_no_date'			=> "Asked by %s",
	'forum_rss_title_topics'		=> "%s Latest Topics",
	'forum_rss_title_questions'		=> "%s Latest Questions",
	'first_post'					=> "First post",
	'latest_post'					=> "Latest post",
	'latest_answer'					=> "Latest answer",
	'first_unread_post_hover'		=> "First unread",
	'best_answer_post'				=> "Best answer",
	'topic_started_by'				=> "Started by %s",
	'topic'							=> "Topic",
	'answer_count'					=> "{# [1:answer][?:answers]} to this question",
	'reply_count'					=> "{# [1:post][?:posts]} in this topic",
	'best_answer_tooltip'			=> "Best answer to this question",
	'vote_answer_up'				=> "Vote this answer up",
	'vote_answer_down'				=> "Vote this answer down",
	'vote_question_up'				=> "Vote this question up",
	'vote_question_down'			=> "Vote this question down",
	'best_answers'					=> "Best Answers",
	'set_as_best_answer'			=> "Mark this as a best answer",
	'unset_as_best_answer'			=> "Unset as best answer",
	'sort_by_answers'				=> "Sort by votes",
	'sort_by_date'					=> "Sort by date",
	'select_forum'					=> "Select Forum",
	'create_new_topic'				=> "Create New Topic",
	'ask_new_question'				=> "Ask New Question",
	'no_answers'					=> "There have been no answers to this question yet",
	'no_forum_posts'				=> "No posts here yet",
	'no_forum_posts_password'		=> "No posts to show",
	'no_posts_returned'				=> "There are no posts to show",
	'topic_pl'						=> "Topics",
	'topic_pl_lc'					=> "topics",
	'post_pl'						=> "Posts",
	'post_pl_lc'					=> "posts",
	'archivedpost_pl'				=> "Archived Posts",
	'archivedpost_pl_lc'			=> "archived posts",
	'topic__comment_placeholder'	=> "Reply to this topic...",
	'question__comment_placeholder'	=> "Answer this question...",
	'moderator_actions'				=> "Moderation Actions",
	'toggle_this_category'			=> "Toggle this category",
	'topic_locked'					=> "This topic is locked",
	'topic_pinned'					=> "This topic is pinned",
	'topic_hidden'					=> "This topic is hidden",
	'topic_featured'				=> "This topic is featured",
	'create_topic_locked'			=> "Lock topic",
	'create_topic_pinned'			=> "Pin topic",
	'create_topic_hidden'			=> "Hide topic",
	'create_topic_featured'			=> "Feature topic",
	'mark_topic_read'				=> "Mark this topic read",
	'answered'						=> "Has best answer",
	'awaiting_answer'				=> "Awaiting best answer",
	'forum_requires_password'		=> "Enter password for %s",
	'enter_forum'					=> "Enter forum",
	'enter_forum_password_1'		=> "Viewing %s requires a password. If you know it, enter it below.",
	'forums_comments'				=> "{!# [1:reply][?:replies]}",
	'forums_num_views'				=> "{!# [1:view][?:views]}",
	'share_this_post'				=> "Share this post",
	'subforums'						=> "Subforums:",
	'subforums_header'				=> "Subforums",
	'subforums_header_category'		=> "Forums",
	'reply_to_topic'				=> "Reply to this topic",
	'answer_this_question'			=> "Answer this question",
	'link_to_post'					=> "Link to post",
	'share_externally'				=> "Share on other sites",
	'featured_topics'				=> "Featured Topics",
	'no_new_posts'					=> "No new posts in this topic",
	'new_posts'						=> "New posts in this topic",
	'featured_question'				=> "Featured Question",
	'featured_topic'				=> "Featured Topic",
	'next_question'					=> "Next question",
	'next_topic'					=> "Next topic",
	'prev_question'					=> "Previous question",
	'prev_topic'					=> "Previous topic",
	'topic_create_state'			=> "After posting...",
	'topic_information'				=> "Topic Information",
	'topic_moderator_options'		=> "Moderator Options",
	'submit_question'				=> "Submit Question",
	'submit_topic'					=> "Submit Topic",
	'submit_topic_edit'				=> "Edit Topic",
	'submit_question_edit'			=> "Edit Question",
	'topic_submit_comment'			=> "Submit Reply",
	'edit_question'					=> "Edit Question",
	'edit_topic'					=> "Edit Topic",
	'edit_reply'					=> "Edit Post",
	'go_to_forum'					=> "Go to %s",
	'go_back_to_forum'				=> "Go To Topic Listing",
	'go_back_to_qa_forum'			=> "Go To Question Listing",
	'first_unread_post'				=> "Go to first unread post",
	'get_last_post'					=> "Go to last post",
	'topic_is_archived'				=> "Archived",
	'topic_archived_desc'			=> "This topic is now archived and is closed to further replies.",
	'count_topics_in_forum'			=> "{# [1:topic][?:topics] in this forum}",
	'count_questions_in_forum'		=> "{# [1:question][?:questions] in this forum}",
	'view_next_unread'				=> "Next unread topic",
	'view_next_unread_question'		=> "Next unread question",
	'view_next_unread_title'		=> "Go to the next topic that has new content",
	'view_next_unread_question_title' => "Go to the next question that has new answers",
	'hide_all_signatures'			=> "Hide all signatures",
	'hide_members_signature'		=> "Hide %s's signature",
	'go_to_new_location'			=> "Go to this topic in its new location",
	'topic_moved_to'				=> "Topic was moved to forum <a href='%s'><strong>%s</strong></a>",
	'question_moved_to'				=> "Question was moved to forum <a href='%s'><strong>%s</strong></a>",
	'topic_merged_to'				=> "Topic was merged with <a href='%s'><strong>%s</strong></a>",
	'question_merged_to'			=> "Question was merged with <a href='%s'><strong>%s</strong></a>",
	'this_topic'					=> "This Topic",
	'this_forum'					=> "This Forum",
	'forum_id'						=> "Forum",
	'announce_forums'				=> "Forums",
	'embed_topic'					=> "Forum Topic",
	'questions_with_best_answers'	=> "Questions With Best Answers",
	'questions_without_best_answers'=> "Questions Without Best Answers",
	'this_is_a_popular_post'		=> "This is a popular post.",
	'rate_this_topic'				=> "Rate this topic",
	'rate_this_question'			=> "Rate this question",
	'sign_in_rate_question'			=> "Sign in to rate this question",
	'sign_in_rate_answer'			=> "Sign in to rate this answer",
	'no_questions_in_forum'			=> "There are no questions in this forum yet",
	'no_topics_in_forum'			=> "There are no topics in this forum yet",
	'submit_first_question'			=> "Ask the first question",
	'submit_first_topic'			=> "Start the first topic",
	'topic_pending_approval'		=> "This topic is not yet approved and is currently only visible to staff.",
	'topic_locked_can_comment'		=> "This topic is locked, but your permissions allow you to add new replies.",
	'topic_poll_can_comment'		=> "This is a poll-only topic, but your permissions allow you to add new replies.",
	'topic_locked_cannot_comment'	=> "This topic is now closed to further replies.",
	'ip_prefix'						=> "IP: %s",
	'popular_questions_title'		=> "Popular questions from the past month",
	'no_popular_questions'			=> "There are no popular questions to show right now",
	'new_questions_title_no_answer'	=> "Questions with no answers",
	'new_questions_title_no_best'	=> "Questions with no best answer",
	'no_new_questions'				=> "There are no new questions to show right now",
	'topic_delete_title'			=> "Delete this topic",
	'approve_title_topic'			=> "Approve this topic",
	'no_perm_topic_password'		=> "This topic cannot be displayed because it is in a password protected forum.",
	'no_perm_topic_min_posts'		=> "This topic cannot be displayed because it is in a forum which requires at least {# [1:post][?:posts]} to view.",
	'no_perm_post_password'			=> "This post cannot be displayed because it is in a password protected forum.",
	'no_perm_post_min_posts'		=> "This post cannot be displayed because it is in a forum which requires at least {# [1:post][?:posts]} to view.",
	'enter_password'				=> "Enter Password",
	'topic_unlocks_at'				=> "Topic will be automatically unlocked %s at %s",
	'topic_unlocks_at_short'		=> "Unlocks %s",
	'topic_locks_at'				=> "Topic will be automatically locked %s at %s",
	'topic_locks_at_short'			=> "Locks %s",
	
	/* !Saved Actions */
	'saved_actions'					=> "Saved Actions",
	'saved_actions_sg'				=> "Saved Action",
	'mm_title'						=> "Name",
	'mm_forums'						=> "Forums",
	'topic_properties'				=> "Properties",
	'mm_leave'						=> "Do not change",
	'topic_state'					=> "Lock/Unlock",
	'topic_pin'						=> "Pin/Unpin",
	'topic_approve'					=> "Hide/Unhide",
	'topic_move'					=> "Move To",
	'topic_move_none'				=> "Do not move",
	'topic_move_link'				=> "Leave a link to the new location?",
	'topic_title_st'				=> "Add to the start of the title",
	'topic_title_end'				=> "Add to the end of the title",
	'add_reply'						=> "Add Reply",
	'topic_reply'					=> "Add reply?",
	'topic_reply_content'			=> "Reply",
	'topic_reply_postcount'			=> "Increment post count?",
	'can_use_saved_actions'			=> "Can use saved actions?",
	'modlog__saved_action'			=> "Ran \"%s\" saved action on topic: <a href='%s'>%s</a>",
	'modlog__unarchived_topic'		=> "Unarchived topic: <a href='%s'>%s</a>",
	'modlog__removed_archive_exclude_topic'	=> "Removed 'exlude from archive' state from topic: <a href='%s'>%s</a>",


	
	/* !Tasks */
	'task__rssimport'				=> "Checks RSS/Atom feeds for new articles and imports into Forums.",
	'queue_deleting_legacy_topics'	=> "Deleting legacy topic data",
	'queue_deleting_legacy_posts'	=> "Deleting legacy post data",
	'queue_fixing_hidden_first_post' => "Updating incorrectly hidden topics",
	'queue_rebuilding_new_topic_flag' => "Rebuilding new topic flag in posts",
	
	/* !Sidebar */
	'block_forumStatistics'			=> "Forum Statistics",
	'block_forumStatistics_desc'	=> "Shows general forum statistics",
	'total_topics'					=> "Total Topics",
	'total_posts'					=> "Total Posts",
	'block_latestTopics'			=> "Latest Topics",
	'block_latestTopics_desc'		=> "Show the latest topics posted",
	'view_this_topic'				=> "View the topic %s",
	'block_hotTopics'				=> "Popular Now",
	'block_hotTopics_desc'			=> "Show topics that are currently popular",
	'block_featuredTopics'			=> "Featured Topics",
	'block_featuredTopics_desc'		=> "Show topics that are currently featured",
	'block_topicFeed'				=> "Topic Feed",
	'block_topicFeed_desc'			=> "Create a feed of topics based on custom sort and order options",
	'block_postFeed'				=> "Post Feed",
	'block_postFeed_desc'			=> "Create a feed of posts based on custom sort and order options",
	
	/* !Digests */
	'digest_area_forums_topic'		=> "Topics",
	'digest_area_forums_forum'		=> "Forums",
	'x_created_topic_in'	=> "%s created a topic in %s",
	'x_asked_new_question'	=> "%s asked a new question in %s",
	'x_replied_to_a_topic'	=> "%s replied to a topic",
	'x_answered_a_question' => "%s answered a question",
		
	/* !Online User Locations */
	'loc_forums_viewing_topic'	=> "Viewing Topic: %s",
	'loc_forums_viewing_forum'	=> "Viewing Forum: %s",	
	'loc_forums_creating_topic'	=> "Creating Topic in: %s",
	'loc_forums_index'			=> "Viewing Forums Index",

	/* Advertisements */
	'ad_forum_listing'			=> "After the first topic in each forum",
	'ad_topic_view'				=> "After the first post in each topic",
	'ad_fluid_index_view'		=> "Fluid view topic listing, between topic rows",
	'ad_fluid_index_view_number' => "Show this advert after every",
	'ad_fluid_index_view_number_suffix' => "topic rows when in fluid view mode",
	'ad_fluid_index_view_repeat'	=> "Repeated",
	'ad_fluid_index_view_repeat_suffix' => "times",
	
	/* !Statistics */
	'stats_new_topics'	=> "New Topics",
	'stats_new_posts'	=> "New Posts",
	
	'stats_topics_title'	=> "New topics by time period",
	'stats_posts_title'		=> "New posts by time period",
	
	/* !Topic/Post Feed Block Config */
	'widget_feed_container_topic'	=> "Forums",
	'block_topicFeed_title'	      => "Topics",
	'block_postFeed_title'		  => "Posts",	
	'rssimport_task_error'			=> "Attempting to import the feed failed with the following message: %s",
	
	/* Poll block */
	'block_poll'					 => "Poll",
	'block_poll_desc'				 => "Create a block with a poll from a topic",
	'widget_poll_tid'				 => "Topic",
	'widget_poll_tid_desc'			 => "Start typing the name of the topic",
	'poll_view_topic'					 => "View topic",
	
	/* !API */
	'__api_forums_posts'			=> "Posts",
	'__api_forums_topics'			=> "Topics",
	'__api_forums_forums'			=> "Forums",

	/* !Meta */
	'recommend_post'				=> "Recommend Post",
	'recommended_posts'				=> "Recommended Posts",
	
	/* !Simple view */
	'forums_simple_name_with_container'	=> "By %s in <a href='%s'>%s</a>",
	'forums_show_all_forums'		 => "Table view",
	'forums_show_all_forums_tooltip' => "Show a table of categories and forums",
	'forum_simple_view_last_post' => "Last action",
	'forums_show_fluid_forums'	=> "Fluid View",
	'forums_show_fluid_forums_tooltip' => "Show all topics with a forum filter box",
	'forums_simple_view_change_tooltip' => "Change view",
	'forums_simple_filter_by' => 'Filter topics by forum',
	'forums_simple_dialog_title' => 'Filter by forum',
	'done_forum_filtering'	=> "Done",
	'forums_chosen_forums' => "These Forums",
);

